  - name: install docker.io
    apt:
      update_cache: yes
      name: docker.io
      state: present
  - name: install python3-pip
    apt:
      name: python3-pip
      state: present
  - name: docker
    pip:
      name: docker
      state: present
  - name: cyberxsecurity/dvwa container
    community.docker.docker_container:
      name: cyberxsecurity_dvwa
      image: cyberxsecurity/dvwa
      state: started
      ports: 80:80
      restart_policy: always
  - name: systemd
    systemd:
      name: docker
      enabled: yes
